name: Build Debug APK (#${{ github.run_number }})

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANNICT_CLIENT_SECRET: ${{ secrets.ANNICT_CLIENT_SECRET }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode debug keystore
        run: |
          mkdir -p app
          printf '%s' "${{ secrets.DEBUG_KEYSTORE_BASE64 }}" | base64 -d > app/debug.keystore

      - name: Build APK
        run: ./gradlew assembleDebug -PannictClientSecret="$ANNICT_CLIENT_SECRET" --stacktrace

      - name: Get timestamp
        id: timestamp
        run: echo "value=$(date +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT

      - name: Rename APK
        run: mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/app-debug-${{ steps.timestamp.outputs.value }}.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-${{ steps.timestamp.outputs.value }}
          path: app/build/outputs/apk/debug/app-debug-${{ steps.timestamp.outputs.value }}.apk