name: Build Debug APK

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: -Dorg.gradle.configuration-cache=false
      ANNICT_CLIENT_ID: ${{ secrets.ANNICT_CLIENT_ID }}
      ANNICT_CLIENT_SECRET: ${{ secrets.ANNICT_CLIENT_SECRET }}
      MAL_CLIENT_ID: ${{ secrets.MAL_CLIENT_ID }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode debug keystore
        run: |
          mkdir -p app
          printf '%s' "${{ secrets.DEBUG_KEYSTORE_BASE64 }}" | base64 -d > app/debug.keystore

      - name: Get timestamp
        id: timestamp
        run: echo "value=$(date +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT

      - name: Build APK
        env:
          BUILD_TIMESTAMP: ${{ steps.timestamp.outputs.value }}
          BUILD_REF_NAME: ${{ github.head_ref || github.ref_name }}
        run: ./gradlew assembleDebug -PannictClientId="$ANNICT_CLIENT_ID" -PannictClientSecret="$ANNICT_CLIENT_SECRET" -PannictClientSecret="$MAL_CLIENT_ID" --stacktrace

      - name: Rename APK
        run: mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/app-debug-${{ steps.timestamp.outputs.value }}.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-${{ steps.timestamp.outputs.value }}
          path: app/build/outputs/apk/debug/app-debug-${{ steps.timestamp.outputs.value }}.apk
          retention-days: 7