name: Test and Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: -Dorg.gradle.configuration-cache=false
      ANNICT_CLIENT_SECRET: ${{ secrets.ANNICT_CLIENT_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run ktlint
        run: ./gradlew ktlintCheck

      - name: Run detekt
        run: ./gradlew detekt

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

#      - name: Run UI tests
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: 33
#          script: ./gradlew connectedDebugAndroidTest

      - name: Build APK
        run: ./gradlew assembleDebug -PannictClientSecret="$ANNICT_CLIENT_SECRET" --stacktrace

      - name: Get timestamp
        id: timestamp
        run: echo "value=$(date +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT

      - name: Rename debug APK
        run: mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/app-debug-${{ steps.timestamp.outputs.value }}.apk

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-${{ steps.timestamp.outputs.value }}
          path: app/build/outputs/apk/debug/app-debug-${{ steps.timestamp.outputs.value }}.apk
