name: Test and Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: -Dorg.gradle.configuration-cache=false
      ANNICT_CLIENT_SECRET: 'dummy'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run ktlint
        run: ./gradlew ktlintCheck

      - name: Run detekt
        run: ./gradlew detekt

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

#      - name: Run UI tests
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: 33
#          script: ./gradlew connectedDebugAndroidTest